plugins {
    id 'java'
    id 'groovy'
    id 'org.jetbrains.kotlin.jvm' version '1.9.20'
}

kotlin {
    jvmToolchain(17)
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.apache.groovy:groovy-test:4.0.5'
        force 'org.apache.groovy:groovy-json:4.0.5'
        force 'org.apache.groovy:groovy-datetime:4.0.5'
        force 'org.apache.groovy:groovy-xml:4.0.5'
        force 'org.apache.groovy:groovy-templates:4.0.5'
    }
}

allprojects {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs += ['-Xlint:deprecation']
    }
}

repositories {
    mavenCentral()
    maven { url 'https://repo.grails.org/grails/core' }
    maven {
        url 'https://artifactory.exalate.com/artifactory/all'
        credentials {
            username = findProperty("artifactoryUsername")
            password = findProperty("artifactoryPassword")
        }
    }
}

dependencies {
    // Keep existing dependencies as they are well-configured
    implementation fileTree(dir: 'lib', include: ['*.jar'])
    implementation 'org.apache.groovy:groovy-all:4.0.5'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.2.1'
    implementation 'org.springframework:spring-context:6.1.14'
    implementation 'org.springframework:spring-webflux:6.1.14'
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'

    // Fat jar containing all the exalate dependencies
    implementation 'com.exalate:customconnectornode_2.13:5.22.0-m13'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'org.apache.groovy:groovy-test:4.0.5'
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'

    testImplementation 'org.mockito:mockito-core:4.11.0'
    testImplementation 'org.objenesis:objenesis:3.3'
    testImplementation 'net.bytebuddy:byte-buddy:1.14.9'
    testImplementation 'org.apache.groovy:groovy:4.0.5'
    testImplementation 'org.apache.groovy:groovy-test-junit5:4.0.5'
}

test {
    useJUnitPlatform()
}


tasks.register('groovyJar', Jar) {
    archiveBaseName = 'discourse-api-groovy'
    from sourceSets.main.groovy
    include '**/*.groovy'
    manifest {
        attributes(
                'Main-Class': 'customconnectornode.discourse.DiscourseApi'
        )
    }
}